CREATE DATABASE AuraBank;
USE AuraBank;
CREATE TABLE UserLogin(
	UserId INT PRIMARY KEY IDENTITY(1,1),
	UserName VARCHAR(100) UNIQUE,
	Balance INT DEFAULT 1000,);
SELECT * FROM UserLogin;

ALTER TABLE UserLogin ADD Password VARCHAR(225);
